sudo: required

dist: xenial

language: node_js

node_js: "8"

osx_image: xcode8.3

matrix:
  include:
    - os: osx
    - os: linux
    
env:
- ELECTRON_CACHE=$HOME/.electron

cache:
  directories:
  - node_modules
  - "$HOME/Library/Caches/electron"
  - "$HOME/Library/Caches/electron-builder"

addons:
  apt:
    packages:
      - xvfb
      - rpm

install:
  - npm install electron-builder@next
  - npm install
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - if [[ ("$TRAVIS_OS_NAME" == "linux") ]]; then sudo snap install snapcraft --classic; fi

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3

script:
  - if [[ ("$TRAVIS_OS_NAME" == "linux") && ("$TRAVIS_TAG" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.linux$) ]]; then npm run dist:linux; fi
  - if [[ ("$TRAVIS_OS_NAME" == "osx") && ("$TRAVIS_TAG" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.osx$)  ]]; then npm run dist:osx; fi

before_cache:
  - rm -rf $HOME/Library/Caches/electron-builder

deploy:
    provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: $TRAVIS_BUILD_DIR/dist/*
    skip_cleanup: true
    on:
        repo: 
        rrhythmsharma/electron-travis-ci