sudo: false

dist: trusty

osx_image: xcode10.1

language: node_js

node_js: "8"

env:
- ELECTRON_CACHE=$HOME/.electron

cache:
  directories:
  - node_modules
  - "$HOME/Library/Caches/electron"
  - "$HOME/Library/Caches/electron-builder"

addons:
  apt:
    packages:
      - xvfb
      - rem

install:
  - npm install electron-builder@next
  - npm install
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3

script:
  - npm run dist

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

deploy:
     provider: releases
     api_key: $GITHUB_TOKEN
     file: 
         - ./dist/*
     skip_cleanup: true
     on:
         repo: 
          rrhythmsharma/electron-travis-ci