sudo: false

dist: trusty

language: node_js

node_js: "8"

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  directories:
   - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder


addons:
  apt:
    packages:
      - xvfb

install:
  - npm install electron-builder@next
  - npm install
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3

jobs:
  include:
    - stage: Test
      script: 
        - npm test
    
    - stage: Deploy Windows & Mac
      os: osx
      osx_image: xcode10.1
      script:
        - npm run release -- --mac --win
      # before_cache:
      #   - rm -rf $HOME/.cache/electron-builder/wine

    - stage: Deploy linux
      os: linux
      dist: trusty
      script:
        - npm run release

deploy:
     provider: releases
     api_key: $GITHUB_TOKEN
     file: 
         - ./node_modules/*
         - $HOME/.cache/electron/*
         - $HOME/.cache/electron-builder/* 
     skip_cleanup: true
     on:
         repo: 
          rrhythmsharma/electron-travis-ci