sudo: required
dist: trusty

language: node_js

node_js:
  -  "stable"

os:
- osx
- linux

cache:
  directories:
    - node_modules

install:
  - npm install electron-builder@next
  - npm install

script:
  - npm run dist
