sudo: required

dist: trusty

language: node_js

node_js: "8"

osx_image: xcode8.3

matrix:
  include:
    - os: osx
    - os: linux
    
env:
- ELECTRON_CACHE=$HOME/.electron

cache:
  directories:
  - node_modules
  - "$HOME/Library/Caches/electron"
  - "$HOME/Library/Caches/electron-builder"

addons:
  apt:
    packages:
      - xvfb
      - rpm

install:
  - npm install electron-builder@next
  - npm install
  - sudo snap install snapcraft --classic
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run dist:linux; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run dist:osx; fi

after_script:
  - echo $HOME/Library/Caches/electron-builder
  - echo dist

before_cache:
  - rm -rf $HOME/Library/Caches/electron-builder

deploy:
     provider: releases
     api_key: $GITHUB_TOKEN
     file: 
         - dist/electron-quick-start-1.2.0.AppImage
         - dist/electron-quick-start-1.2.0.x86_64.rpm
         - dist/electron-quick-start-1.2.0.linux-x64.zip
         - dist/electron-quick-start-1.2.0.dmg
     skip_cleanup: true
     on:
         repo: 
          rrhythmsharma/electron-travis-ci