sudo: false

dist: trusty

language: node_js

node_js: 
  - "8"

os:
- linux
- osx

cache:
  yarn: true
  directories:
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds

addons:
  apt:
    packages:
      - xvfb

install:
  - npm install electron-builder@next
  - npm install
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - yarn

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3

script: 
  echo "Hello Travis"
  - npm test
  - npm run release:all

deploy:
     provider: releases
     api_key: $GITHUB_TOKEN
     file: 
         - ./dist/*
     skip_cleanup: true
     on:
         repo: 
          rrhythmsharma/electron-travis-ci