sudo: false

language: node_js
node_js: "9.11.1"

before_install:
  - cd app

cache:
  directories:
    - node_modules
    - app/node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

jobs:
  include:
    - stage: Test
      script: 
        - npm test
    - stage: Update application info
      if: tag IS present
      script:
        - sh ../.travis-update-app-package-version.sh
    - stage: Deploy Windows & Mac
      if: tag IS present
      os: osx
      osx_image: xcode10.1
      script:
        - newVersion=$(git describe --abbrev=0)
        - npm version $newVersion
        - npm run release -- --mac --win
      before_cache:
        - rm -rf $HOME/.cache/electron-builder/wine
    - stage: Deploy linux
      if: tag IS present
      os: linux
      dist: trusty
      script:
        - newVersion=$(git describe --abbrev=0)
        - npm version $newVersion
        - npm run release
