# sudo: false

# dist: trusty

matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: "8"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

    - os: linux
      services: docker
      language: node_js

cache:
  directories:
   - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder


addons:
  apt:
    packages:
      - xvfb

install:
  - npm install electron-builder@next
  - npm install
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3

script: 
  echo "Hello Travis"
   - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      docker run --rm \
        --env-file <(env | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS|APPVEYOR_|CSC_|_TOKEN|_KEY|AWS_|STRIP|BUILD_') \
        -v ${PWD}:/project \
        -v ~/.cache/electron:/root/.cache/electron \
        -v ~/.cache/electron-builder:/root/.cache/electron-builder \
        electronuserland/builder:wine \
        /bin/bash -c "npm --link-duplicates --pure-lockfile && npm run release --linux --win"
    else
      npm run release
    fi

deploy:
     provider: releases
     api_key: $GITHUB_TOKEN
     file: 
         - ./node_modules/*
         - $HOME/.cache/electron/*
         - $HOME/.cache/electron-builder/* 
     skip_cleanup: true
     on:
         repo: 
          rrhythmsharma/electron-travis-ci